### ISSUE TITLE
Great app, can you create an AUR package for Arch Linux?

### ISSUE THREAD

**Issue by Hikandy** [RadioNoiseE/exposway#1]
Can you create an AUR package for Arch Linux? The installation would be very easy!

**Comment by RadioNoiseE** [comment]
> Can you create an AUR package for Arch Linux? The installation would be very easy!

Currently not planning, as I do not use Arch (I'm using gentoo, and an ebuild is in my plan). Anyway, I think the current installation process is quite simple.

**Comment by RadioNoiseE** [comment]
Fell free to write one and submit to AUR.
